#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Map Generator 2.0

set -e

echo "========================================"
echo "Map Generator 2.0 - Development Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Project root
PROJECT_ROOT="/Users/jean/Github/life-simulator"
cd "$PROJECT_ROOT"

echo ""
echo -e "${BLUE}Step 1: Verifying Rust toolchain...${NC}"
if command -v cargo &> /dev/null; then
    echo -e "${GREEN}  ✓ Cargo found: $(cargo --version)${NC}"
else
    echo -e "${RED}  ✗ Cargo not found. Please install Rust first.${NC}"
    exit 1
fi

echo ""
echo -e "${BLUE}Step 2: Building project...${NC}"
cargo build --bin life-simulator --bin map_generator 2>&1 | tail -5
if [ $? -eq 0 ]; then
    echo -e "${GREEN}  ✓ Build successful${NC}"
else
    echo -e "${RED}  ✗ Build failed${NC}"
    exit 1
fi

echo ""
echo -e "${BLUE}Step 3: Running tests...${NC}"
cargo test --lib 2>&1 | tail -5
if [ $? -eq 0 ]; then
    echo -e "${GREEN}  ✓ Tests passed${NC}"
else
    echo -e "${YELLOW}  ⚠ Some tests may have failed - check output${NC}"
fi

echo ""
echo -e "${BLUE}Step 4: Verifying map generator...${NC}"
cargo run --bin map_generator -- list 2>&1 | head -10
echo -e "${GREEN}  ✓ Map generator ready${NC}"

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Available commands:"
echo ""
echo "  ${YELLOW}Generate a map:${NC}"
echo "    cargo run --bin map_generator generate my_world 'My World' 12345"
echo ""
echo "  ${YELLOW}List saved maps:${NC}"
echo "    cargo run --bin map_generator list"
echo ""
echo "  ${YELLOW}Start simulation:${NC}"
echo "    cargo run --release --bin life-simulator"
echo ""
echo "  ${YELLOW}Run tests:${NC}"
echo "    cargo test --lib"
echo ""
echo "  ${YELLOW}View in browser:${NC}"
echo "    http://localhost:54321/viewer.html"
echo ""
echo "========================================"
echo "Pre-Implementation Safety Checklist:"
echo "========================================"
echo ""
echo "  ${RED}BEFORE making any code changes:${NC}"
echo ""
echo "  1. Create snapshot tag:"
echo "     git tag -a pre-mapgen2.0 -m 'Snapshot before Map Generator 2.0 implementation'"
echo ""
echo "  2. Verify current state works:"
echo "     cargo test --lib && cargo run --bin map_generator generate test_snapshot TestSnapshot 12345"
echo ""
echo "  3. Push tag to remote (optional):"
echo "     git push origin pre-mapgen2.0"
echo ""
echo "========================================"
